import { PROJECTS_MEDIA } from '@/data/assets';
import { PROJECTS } from '@/data/content';
import { Section } from '@/components/ui/Section';
import { GlassCard } from '@/components/ui/GlassCard';
import { Chip } from '@/components/ui/Bits';
import { Icon } from '@/components/ui/Icon';

const MEDIA = [PROJECTS_MEDIA.model3d, PROJECTS_MEDIA.fileUi];
const MEDIA_ALT = [
  'An isometric 3D render of a multi-storey house generated by the planning platform',
  'The file collaboration platform showing a project file list, version history and activity feed',
];

/** 04 — Projects. Two case cards, each pairing the write-up with its render. */
export function Projects({ className = '' }) {
  return (
    <Section
      className={className}
      id="projects"
      number="04"
      title="Projects"
      caption="Turning ideas into impact"
      bodyClassName="space-y-5"
    >
      {PROJECTS.map((project, i) => (
        <GlassCard key={project.number} variant="inset" className="overflow-hidden">
          <div className="grid gap-0 lg:grid-cols-[1.05fr_0.95fr]">
            {/* --- write-up --- */}
            <div className="p-5 sm:p-6">
              <div className="flex items-start gap-4">
                <span className="font-display text-3xl leading-none text-bone-500">
                  {project.number}
                </span>
                <h3 className="mt-0.5 max-w-[18ch] font-display text-xl uppercase leading-[1.14] text-bone-50 sm:text-2xl">
                  {project.title}
                </h3>
              </div>

              <ul className="mt-4 flex flex-wrap gap-2">
                {project.tags.map((tag) => (
                  <li key={tag}>
                    <Chip>{tag}</Chip>
                  </li>
                ))}
              </ul>

              <p className="mt-4 max-w-[48ch] text-sm leading-[1.8] text-bone-300">
                {project.summary}
              </p>

              {project.metric ? (
                <p className="mt-6 flex items-baseline gap-3">
                  <span className="font-display text-4xl text-bone-50 sm:text-5xl">
                    {project.metric.value}
                  </span>
                  <span className="font-mono text-2xs uppercase tracking-widest2 text-bone-400">
                    {project.metric.label}
                  </span>
                </p>
              ) : null}

              {project.features ? (
                <ul className="mt-5 space-y-2">
                  {project.features.map((feature) => (
                    <li key={feature} className="flex items-center gap-2.5 text-sm text-bone-300">
                      <Icon name="check" size={13} className="shrink-0 text-brass-400/80" />
                      {feature}
                    </li>
                  ))}
                </ul>
              ) : null}

              {project.cta ? (
                <a
                  href={project.cta.href}
                  className="btn-motion group mt-6 inline-flex items-center gap-2.5 rounded-full border border-bone-500/45 px-4 py-2 text-sm text-bone-100 hover:border-brass-400/60 hover:bg-brass-500/[0.06] hover:text-brass-400"
                >
                  {project.cta.label}
                  <Icon
                    name="arrow"
                    size={14}
                    className="transition-transform duration-500 ease-museum group-hover:translate-x-1"
                  />
                </a>
              ) : null}
            </div>

            {/* --- render --- */}
            <figure className="relative min-h-[220px] border-t border-bone-500/20 lg:border-l lg:border-t-0">
              <img
                src={MEDIA[i]}
                alt={MEDIA_ALT[i]}
                loading="lazy"
                decoding="async"
                className="h-full w-full object-cover object-center"
              />
              <div
                aria-hidden="true"
                className="absolute inset-0 bg-gradient-to-t from-ink-900/85 via-ink-900/15 to-transparent"
              />

              {project.mediaCaption ? (
                <figcaption className="absolute inset-x-4 bottom-4 flex items-end justify-between gap-4">
                  <span>
                    <span className="block font-mono text-2xs uppercase tracking-widest2 text-bone-300">
                      {project.mediaCaption.title}
                    </span>
                    <span className="mt-1 block text-sm text-bone-200">
                      {project.mediaCaption.body}
                    </span>
                  </span>
                  <Icon name="arrow" size={16} className="mb-1 -rotate-45 text-bone-400" />
                </figcaption>
              ) : null}

              {/* the wireframe crop, layered as a blueprint watermark */}
              {i === 0 ? (
                <div
                  aria-hidden="true"
                  className="pointer-events-none absolute inset-0 opacity-20 mix-blend-screen"
                  style={{
                    backgroundImage: `url(${PROJECTS_MEDIA.wireframe})`,
                    backgroundSize: 'cover',
                    backgroundPosition: 'center',
                  }}
                />
              ) : null}
            </figure>
          </div>
        </GlassCard>
      ))}
    </Section>
  );
}

export default Projects;
